import pluginVue from "eslint-plugin-vue";
import {
  defineConfigWithVueTs,
  vueTsConfigs
} from "@vue/eslint-config-typescript";
import skipFormatting from "@vue/eslint-config-prettier/skip-formatting";

export default defineConfigWithVueTs(
  {
    name: "app/files-to-lint",
    files: ["**/*.{ts,mts,tsx,vue}"]
  },
  {
    name: "app/files-to-ignore",
    ignores: [
      "**/dist/**",
      "**/target/**",
      "**/coverage/**",
      "**/node_modules/**"
    ]
  },
  pluginVue.configs["flat/recommended"],
  vueTsConfigs.recommended,
  skipFormatting,
  {
    name: "app/rules",
    rules: {
      "vue/multi-word-component-names": "off",
      // shadcn-vue components are registered under PascalCase names such as
      // Button, Input or Table; case-sensitive matching keeps the rule from
      // confusing them with the native lowercase HTML elements.
      "vue/no-reserved-component-names": [
        "error",
        { htmlElementCaseSensitive: true }
      ]
    }
  },
  {
    // Generated by the shadcn-vue CLI; keep diffs against upstream minimal.
    name: "app/shadcn-generated",
    files: ["src/components/ui/**"],
    rules: {
      "vue/require-default-prop": "off"
    }
  }
);
