-- Auto-accept rules (owner decision 19): the rule tables and the marker
-- columns of both assertion tables. Generated by drizzle-kit; the two UNIQUE
-- constraints the trigger foreign keys reference were moved before those keys
-- (drizzle-kit emits them last, which PostgreSQL refuses).
CREATE TABLE "auto_accept_rule" (
	"id" text PRIMARY KEY NOT NULL,
	"project_id" text NOT NULL,
	"kind" text NOT NULL,
	"created_by" text NOT NULL,
	"seq" bigint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "auto_accept_rule_project_id_unique" UNIQUE("project_id","id"),
	CONSTRAINT "auto_accept_rule_project_id_kind_unique" UNIQUE("project_id","id","kind"),
	CONSTRAINT "auto_accept_rule_kind_check" CHECK ("auto_accept_rule"."kind" in ('relation', 'placement'))
);
--> statement-breakpoint
CREATE TABLE "auto_accept_rule_revision" (
	"project_id" text NOT NULL,
	"rule_id" text NOT NULL,
	"kind" text NOT NULL,
	"revision" integer NOT NULL,
	"name" text NOT NULL,
	"enabled" boolean NOT NULL,
	"tier" text NOT NULL,
	"min_confidence" double precision NOT NULL,
	"note" text,
	"relation_type" text,
	"agent_principal_id" text,
	"llm_model" text,
	"include_ad_hoc" boolean DEFAULT false NOT NULL,
	"principal_id" text NOT NULL,
	"client_id" text,
	"source_kind" text NOT NULL,
	"seq" bigint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "auto_accept_rule_revision_rule_id_revision_pk" PRIMARY KEY("rule_id","revision"),
	CONSTRAINT "auto_accept_rule_revision_project_unique" UNIQUE("project_id","rule_id","revision"),
	CONSTRAINT "auto_accept_rule_revision_author_unique" UNIQUE("project_id","rule_id","revision","principal_id"),
	CONSTRAINT "auto_accept_rule_revision_humans_only" CHECK ("auto_accept_rule_revision"."source_kind" = 'human'),
	CONSTRAINT "auto_accept_rule_revision_revision_check" CHECK ("auto_accept_rule_revision"."revision" >= 1),
	CONSTRAINT "auto_accept_rule_revision_confidence_check" CHECK ("auto_accept_rule_revision"."min_confidence" between 0.5 and 1),
	CONSTRAINT "auto_accept_rule_revision_tier_check" CHECK (("auto_accept_rule_revision"."kind" = 'relation' and "auto_accept_rule_revision"."tier" in ('key', 'lexical', 'semantic')) or ("auto_accept_rule_revision"."kind" = 'placement' and "auto_accept_rule_revision"."tier" in ('lexical', 'semantic') and "auto_accept_rule_revision"."relation_type" is null)),
	CONSTRAINT "auto_accept_rule_revision_type_check" CHECK ("auto_accept_rule_revision"."relation_type" is null or "auto_accept_rule_revision"."relation_type" in ('call', 'message', 'signal', 'trigger')),
	CONSTRAINT "auto_accept_rule_revision_kind_check" CHECK ("auto_accept_rule_revision"."kind" in ('relation', 'placement')),
	CONSTRAINT "auto_accept_rule_revision_name_check" CHECK (char_length("auto_accept_rule_revision"."name") between 1 and 100 and ("auto_accept_rule_revision"."llm_model" is null or char_length("auto_accept_rule_revision"."llm_model") between 1 and 100))
);
--> statement-breakpoint
ALTER TABLE "placement_assertion" ADD COLUMN "auto_accept_rule_id" text;--> statement-breakpoint
ALTER TABLE "placement_assertion" ADD COLUMN "auto_accept_rule_revision" integer;--> statement-breakpoint
ALTER TABLE "placement_assertion" ADD COLUMN "auto_accept_trigger_id" text;--> statement-breakpoint
ALTER TABLE "relation_assertion" ADD COLUMN "auto_accept_rule_id" text;--> statement-breakpoint
ALTER TABLE "relation_assertion" ADD COLUMN "auto_accept_rule_revision" integer;--> statement-breakpoint
ALTER TABLE "relation_assertion" ADD COLUMN "auto_accept_trigger_id" text;--> statement-breakpoint
ALTER TABLE "placement_assertion" ADD CONSTRAINT "placement_assertion_placement_id_unique" UNIQUE("project_id","placement_id","id");--> statement-breakpoint
ALTER TABLE "relation_assertion" ADD CONSTRAINT "relation_assertion_relation_id_unique" UNIQUE("project_id","relation_id","id");--> statement-breakpoint
ALTER TABLE "auto_accept_rule" ADD CONSTRAINT "auto_accept_rule_project_id_project_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."project"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auto_accept_rule" ADD CONSTRAINT "auto_accept_rule_created_by_principal_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."principal"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auto_accept_rule_revision" ADD CONSTRAINT "auto_accept_rule_revision_agent_principal_id_principal_id_fk" FOREIGN KEY ("agent_principal_id") REFERENCES "public"."principal"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auto_accept_rule_revision" ADD CONSTRAINT "auto_accept_rule_revision_principal_id_principal_id_fk" FOREIGN KEY ("principal_id") REFERENCES "public"."principal"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auto_accept_rule_revision" ADD CONSTRAINT "auto_accept_rule_revision_rule_fk" FOREIGN KEY ("project_id","rule_id","kind") REFERENCES "public"."auto_accept_rule"("project_id","id","kind") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "placement_assertion" ADD CONSTRAINT "placement_assertion_auto_accept_rule_fk" FOREIGN KEY ("project_id","auto_accept_rule_id","auto_accept_rule_revision","principal_id") REFERENCES "public"."auto_accept_rule_revision"("project_id","rule_id","revision","principal_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "placement_assertion" ADD CONSTRAINT "placement_assertion_auto_accept_trigger_fk" FOREIGN KEY ("project_id","placement_id","auto_accept_trigger_id") REFERENCES "public"."placement_assertion"("project_id","placement_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "relation_assertion" ADD CONSTRAINT "relation_assertion_auto_accept_rule_fk" FOREIGN KEY ("project_id","auto_accept_rule_id","auto_accept_rule_revision","principal_id") REFERENCES "public"."auto_accept_rule_revision"("project_id","rule_id","revision","principal_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "relation_assertion" ADD CONSTRAINT "relation_assertion_auto_accept_trigger_fk" FOREIGN KEY ("project_id","relation_id","auto_accept_trigger_id") REFERENCES "public"."relation_assertion"("project_id","relation_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "placement_assertion_auto_accept_idx" ON "placement_assertion" USING btree ("project_id","auto_accept_rule_id") WHERE "placement_assertion"."auto_accept_rule_id" is not null;--> statement-breakpoint
CREATE INDEX "relation_assertion_auto_accept_idx" ON "relation_assertion" USING btree ("project_id","auto_accept_rule_id") WHERE "relation_assertion"."auto_accept_rule_id" is not null;--> statement-breakpoint
ALTER TABLE "placement_assertion" ADD CONSTRAINT "placement_assertion_auto_accept_check" CHECK (("placement_assertion"."auto_accept_rule_id" is null) = ("placement_assertion"."auto_accept_rule_revision" is null) and ("placement_assertion"."auto_accept_rule_id" is not null or "placement_assertion"."auto_accept_trigger_id" is null) and ("placement_assertion"."auto_accept_rule_id" is null or ("placement_assertion"."source_kind" = 'human' and (("placement_assertion"."kind" = 'decision' and "placement_assertion"."verdict" = 'accept' and "placement_assertion"."auto_accept_trigger_id" is not null and "placement_assertion"."tier" is null) or ("placement_assertion"."kind" = 'withdrawal' and "placement_assertion"."auto_accept_trigger_id" is null)))));--> statement-breakpoint
ALTER TABLE "relation_assertion" ADD CONSTRAINT "relation_assertion_auto_accept_check" CHECK (("relation_assertion"."auto_accept_rule_id" is null) = ("relation_assertion"."auto_accept_rule_revision" is null) and ("relation_assertion"."auto_accept_rule_id" is not null or "relation_assertion"."auto_accept_trigger_id" is null) and ("relation_assertion"."auto_accept_rule_id" is null or ("relation_assertion"."source_kind" = 'human' and (("relation_assertion"."kind" = 'decision' and "relation_assertion"."verdict" = 'accept' and "relation_assertion"."auto_accept_trigger_id" is not null and "relation_assertion"."tier" is null) or ("relation_assertion"."kind" = 'withdrawal' and "relation_assertion"."auto_accept_trigger_id" is null)))));