/**
 * `@proa/client`: typed REST client for the ProA API, generated by hey-api
 * from the OpenAPI document of `@proa/contracts` (`pnpm --filter
 * @proa/client generate`; never edit `src/generated` by hand).
 *
 * @example
 * const client = createProaClient({ baseUrl: 'http://127.0.0.1:7400', token });
 * const { data, error } = await listProjects({ client });
 */
import { createClient, createConfig, type Client } from './generated/client/index.ts';

export * from './generated/index.ts';
export type { Client } from './generated/client/index.ts';

/** Where a local ProA listens by default (CONCEPT §6, docker/compose.yaml). */
export const DEFAULT_PROA_URL = 'http://127.0.0.1:7400';

export interface ProaClientOptions {
  /** Server origin, e.g. `http://127.0.0.1:7400`; the SDK adds `/api/v1/...`. */
  baseUrl?: string;
  /** Agent token (`proa_at_…`), sent as `Authorization: Bearer`. Omit for the local owner session. */
  token?: string;
  /** Custom fetch, e.g. for tests. */
  fetch?: typeof globalThis.fetch;
}

/** Creates an independent client instance; pass it as `{ client }` to the SDK functions. */
export function createProaClient(options: ProaClientOptions = {}): Client {
  return createClient(
    createConfig({
      baseUrl: (options.baseUrl ?? DEFAULT_PROA_URL).replace(/\/+$/, ''),
      ...(options.token === undefined ? {} : { auth: options.token }),
      ...(options.fetch === undefined ? {} : { fetch: options.fetch }),
    }),
  );
}
