/**
 * Drizzle schema (CONCEPT §2, "PostgreSQL sketch"). Conventions:
 * - camelCase keys in TypeScript, snake_case columns (`casing: 'snake_case'`
 *   in drizzle.config.ts and in `createDatabase`);
 * - ids are typed ULIDs (`prj_…`) in `text` columns, generated by the domain;
 * - child rows carry `project_id` with composite foreign keys
 *   `(project_id, x_id) → parent(project_id, id)`, so a row can never point
 *   into another project;
 * - enumerations are `text` plus a CHECK constraint (no Postgres enums, which
 *   are awkward to migrate);
 * - `event`, `relation_assertion`, `analysis_submission`, `no_link`,
 *   `no_link_withdrawal`, `value_chain_revision` and `placement_assertion`
 *   are append-only (triggers in migrations 0001_append_only.sql,
 *   0005_judge_once_triggers.sql and 0007_value_chain_triggers.sql), and so
 *   are `auto_accept_rule` and `auto_accept_rule_revision` (0010);
 *   `value_chain_step` only ever takes its tombstone (0007); `placement_input`
 *   is mutable memory (M4b).
 *
 * After changing this file run `pnpm --filter @proa/server db:generate` and
 * commit the new migration in `apps/server/drizzle/`.
 */
import {
  AgentScope,
  AssertionKind,
  Engine,
  EndpointState,
  EventDef,
  FactKind,
  FactScope,
  FindingKind,
  RelationStatus,
  RelationType,
  Role,
  SourceKind,
  Tier,
  type DeclaredProcedure,
  type FactAttrs,
  type MessageFlowInfo,
  type ProcessInfo,
  type AnalysisSubmissionResult,
  type RevisionSource,
  type TypedPair,
} from '@proa/contracts';
import { sql, type SQL } from 'drizzle-orm';
import {
  bigint,
  boolean,
  check,
  customType,
  doublePrecision,
  foreignKey,
  index,
  integer,
  jsonb,
  pgTable,
  pgView,
  primaryKey,
  text,
  timestamp,
  unique,
  uniqueIndex,
  type AnyPgColumn,
  type PgTableExtraConfigValue,
} from 'drizzle-orm/pg-core';

import type { PlacementClaim } from '../domain/ports.ts';

/** Raw bytes (`bytea`); revisions keep the uploaded BPMN verbatim. */
const bytea = customType<{ data: Uint8Array; driverData: Buffer }>({
  dataType: () => 'bytea',
  toDriver: (value) => Buffer.from(value.buffer, value.byteOffset, value.byteLength),
  fromDriver: (value) => new Uint8Array(value.buffer, value.byteOffset, value.byteLength),
});

const timestamptz = () => timestamp({ withTimezone: true, mode: 'date' });
const createdAt = () => timestamptz().notNull().defaultNow();
/** Event sequence numbers (`project.last_seq`); bigint, read as number (< 2^53). */
const seqColumn = () => bigint({ mode: 'number' });

/** zod enum options as the non-empty tuple drizzle's `text({ enum })` wants. */
function values<T extends string>(options: readonly T[]): readonly [T, ...T[]] {
  return options as unknown as readonly [T, ...T[]];
}

/** `col in ('a', 'b')` for CHECK constraints. Values are code constants, never user input. */
function oneOf(column: AnyPgColumn, values: readonly string[]): SQL {
  const list = values.map((v) => `'${v.replaceAll("'", "''")}'`).join(', ');
  return sql`${column} in (${sql.raw(list)})`;
}

/**
 * The auto-accept marker of an assertion (owner decision 19): rule id and
 * revision come together; only a marked row has a trigger; a marked row is
 * either a human acceptance with its trigger and no tier (the rule's
 * decision) or a human withdrawal without one (its revocation).
 */
function autoAcceptCheck(t: {
  autoAcceptRuleId: AnyPgColumn;
  autoAcceptRuleRevision: AnyPgColumn;
  autoAcceptTriggerId: AnyPgColumn;
  sourceKind: AnyPgColumn;
  kind: AnyPgColumn;
  verdict: AnyPgColumn;
  tier: AnyPgColumn;
}): SQL {
  return sql`(${t.autoAcceptRuleId} is null) = (${t.autoAcceptRuleRevision} is null) and (${t.autoAcceptRuleId} is not null or ${t.autoAcceptTriggerId} is null) and (${t.autoAcceptRuleId} is null or (${t.sourceKind} = 'human' and ((${t.kind} = 'decision' and ${t.verdict} = 'accept' and ${t.autoAcceptTriggerId} is not null and ${t.tier} is null) or (${t.kind} = 'withdrawal' and ${t.autoAcceptTriggerId} is null))))`;
}

export const PRINCIPAL_KINDS = ['user', 'service', 'system'] as const;
export const ASSERTION_KINDS = values(AssertionKind.options);
export const VERDICTS = ['accept', 'reject', 'hold'] as const;
export const TASK_KINDS = ['relations', 'placement'] as const;
/** What a task analyses (M4 §8): a model revision (`relations`) or the value chain (`placement`). */
export const TASK_SUBJECT_KINDS = ['model', 'value_chain'] as const;
/** The agent's last verdict on a process (`placement_input`, M4 §3.2). */
export const PLACEMENT_INPUT_OUTCOMES = ['proposed', 'unsure', 'skipped'] as const;
export const TASK_STATES = ['queued', 'claimed', 'done', 'failed', 'cancelled'] as const;
export const LINK_TYPES = ['call', 'message', 'signal', 'trigger'] as const;
export const JUDGING_SOURCE_KINDS = ['agent', 'human'] as const;
/**
 * Tiers of a placement (M4 §2): server-computed, never `rule` (the rule tier
 * accepts nothing; only an owner's auto-accept rule may accept an agent's
 * placement proposal, recorded as a human decision, owner decision 19).
 */
export const PLACEMENT_TIERS = ['key', 'lexical', 'semantic', 'manual'] as const;
/** What an auto-accept rule accepts (owner decision 19). */
export const AUTO_ACCEPT_KINDS = ['relation', 'placement'] as const;
/** Tiers an auto-accept rule names: relations `key`, `lexical`, `semantic`; placements `lexical`, `semantic`. */
export const AUTO_ACCEPT_TIERS = ['key', 'lexical', 'semantic'] as const;

export const project = pgTable('project', {
  id: text().primaryKey(),
  key: text().notNull().unique(),
  name: text().notNull(),
  /** Last allocated event sequence number (`UPDATE … SET last_seq = last_seq + 1 RETURNING`). */
  lastSeq: seqColumn().notNull().default(0),
  createdAt: createdAt(),
});

export const principal = pgTable(
  'principal',
  {
    id: text().primaryKey(),
    kind: text({ enum: PRINCIPAL_KINDS }).notNull(),
    iss: text().notNull(),
    subject: text().notNull(),
    email: text(),
    handle: text().notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    unique('principal_identity_unique').on(t.iss, t.kind, t.subject),
    check('principal_kind_check', oneOf(t.kind, PRINCIPAL_KINDS)),
  ],
);

export const membership = pgTable(
  'membership',
  {
    projectId: text()
      .notNull()
      .references(() => project.id),
    principalId: text()
      .notNull()
      .references(() => principal.id),
    role: text({ enum: values(Role.options) }).notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    primaryKey({ columns: [t.projectId, t.principalId] }),
    check('membership_role_check', oneOf(t.role, Role.options)),
  ],
);

/** Server mode (R1); unused in M1. */
export const invitation = pgTable(
  'invitation',
  {
    id: text().primaryKey(),
    projectId: text()
      .notNull()
      .references(() => project.id),
    emailNorm: text().notNull(),
    role: text({ enum: values(Role.options) }).notNull(),
    invitedBy: text()
      .notNull()
      .references(() => principal.id),
    expiresAt: timestamptz().notNull(),
    acceptedAt: timestamptz(),
    acceptedBy: text().references(() => principal.id),
    createdAt: createdAt(),
  },
  (t) => [
    unique('invitation_project_id_unique').on(t.projectId, t.id),
    index('invitation_project_email_idx').on(t.projectId, t.emailNorm),
    check('invitation_role_check', oneOf(t.role, Role.options)),
  ],
);

export const agentToken = pgTable(
  'agent_token',
  {
    id: text().primaryKey(),
    projectId: text()
      .notNull()
      .references(() => project.id),
    /** The token's own service principal (`iss = urn:proa:agent-token`). */
    principalId: text()
      .notNull()
      .unique('agent_token_principal_unique')
      .references(() => principal.id),
    name: text().notNull(),
    /** First 8 characters after `proa_at_`. */
    prefix: text().notNull(),
    /** sha256 (hex) of the full secret; the secret itself is never stored. */
    secretHash: text().notNull().unique('agent_token_secret_hash_unique'),
    scopes: text({ enum: values(AgentScope.options) })
      .array()
      .notNull(),
    expiresAt: timestamptz().notNull(),
    revokedAt: timestamptz(),
    createdBy: text()
      .notNull()
      .references(() => principal.id),
    lastUsedAt: timestamptz(),
    createdAt: createdAt(),
  },
  (t) => [
    unique('agent_token_project_id_unique').on(t.projectId, t.id),
    // Agent tokens never carry proa:review (CONCEPT §6).
    check(
      'agent_token_scopes_check',
      sql`cardinality(${t.scopes}) > 0 and ${t.scopes} <@ array[${sql.raw(
        AgentScope.options.map((s) => `'${s}'`).join(', '),
      )}]::text[]`,
    ),
  ],
);

export const model = pgTable(
  'model',
  {
    id: text().primaryKey(),
    projectId: text()
      .notNull()
      .references(() => project.id),
    /** Immutable model key, e.g. `billing/dunning`. */
    key: text().notNull(),
    name: text(),
    /** Null only inside the ingest transaction that creates the model. */
    headRevisionId: text(),
    /** Set when the model is deleted; a later upload of the same key revives it. */
    deletedSeq: seqColumn(),
    createdAt: createdAt(),
    updatedAt: timestamptz().notNull().defaultNow(),
  },
  (t): PgTableExtraConfigValue[] => [
    unique('model_project_key_unique').on(t.projectId, t.key),
    unique('model_project_id_unique').on(t.projectId, t.id),
    foreignKey({
      name: 'model_head_revision_fk',
      columns: [t.projectId, t.headRevisionId],
      foreignColumns: [modelRevision.projectId, modelRevision.id],
    }),
  ],
);

export const modelRevision = pgTable(
  'model_revision',
  {
    id: text().primaryKey(),
    projectId: text().notNull(),
    modelId: text().notNull(),
    rev: integer().notNull(),
    /** The uploaded bytes, verbatim. */
    xml: bytea().notNull(),
    contentHash: text().notNull(),
    factsHash: text().notNull(),
    factsVersion: text().notNull(),
    /** `c7`/`c8` from `ExtractResult.engine`; null if the file names neither (migration 0003 backfills older rows). */
    engine: text({ enum: values(Engine.options) }),
    /** `ExtractResult.processes` and `.messageFlows` of `@proa/bpmn-facts`. */
    processes: jsonb().$type<ProcessInfo[]>().notNull(),
    messageFlows: jsonb().$type<MessageFlowInfo[]>().notNull(),
    source: jsonb().$type<RevisionSource>().notNull(),
    principalId: text()
      .notNull()
      .references(() => principal.id),
    seq: seqColumn().notNull(),
    createdAt: createdAt(),
  },
  (t): PgTableExtraConfigValue[] => [
    unique('model_revision_project_id_unique').on(t.projectId, t.id),
    unique('model_revision_model_rev_unique').on(t.modelId, t.rev),
    check(
      'model_revision_engine_check',
      sql`${t.engine} is null or ${oneOf(t.engine, Engine.options)}`,
    ),
    foreignKey({
      name: 'model_revision_model_fk',
      columns: [t.projectId, t.modelId],
      foreignColumns: [model.projectId, model.id],
    }),
  ],
);

export const fact = pgTable(
  'fact',
  {
    revisionId: text().notNull(),
    projectId: text().notNull(),
    kind: text({ enum: values(FactKind.options) }).notNull(),
    elementId: text().notNull(),
    processId: text(),
    scope: text({ enum: values(FactScope.options) }).notNull(),
    eventDef: text({ enum: values(EventDef.options) }),
    label: text().notNull(),
    keyRaw: text().notNull(),
    keyNorm: text().notNull(),
    fingerprint: text().notNull(),
    attrs: jsonb().$type<FactAttrs>().notNull(),
  },
  (t) => [
    primaryKey({ columns: [t.revisionId, t.kind, t.elementId] }),
    foreignKey({
      name: 'fact_revision_fk',
      columns: [t.projectId, t.revisionId],
      foreignColumns: [modelRevision.projectId, modelRevision.id],
    }),
    // "Which processes throw message X" (CONCEPT §4).
    index('fact_project_kind_key_idx').on(t.projectId, t.kind, t.keyNorm),
    check('fact_kind_check', oneOf(t.kind, FactKind.options)),
    check('fact_scope_check', oneOf(t.scope, FactScope.options)),
    check(
      'fact_event_def_check',
      sql`${t.eventDef} is null or ${oneOf(t.eventDef, EventDef.options)}`,
    ),
  ],
);

export const relation = pgTable(
  'relation',
  {
    id: text().primaryKey(),
    projectId: text()
      .notNull()
      .references(() => project.id),
    type: text({ enum: values(RelationType.options) }).notNull(),
    fromRef: text().notNull(),
    toRef: text().notNull(),
    /** Model keys of both endpoints, for "relations touching model M". */
    fromModel: text()
      .notNull()
      .generatedAlwaysAs(sql`split_part(from_ref, '#', 1)`),
    toModel: text()
      .notNull()
      .generatedAlwaysAs(sql`split_part(to_ref, '#', 1)`),
    status: text({ enum: values(RelationStatus.options) }).notNull(),
    endpointState: text({ enum: values(EndpointState.options) }).notNull(),
    tier: text({ enum: values(Tier.options) }).notNull(),
    confidence: doublePrecision(),
    /** Incremented on every change (optimistic concurrency for decisions, M2). */
    version: integer().notNull().default(1),
    attrs: jsonb().$type<Record<string, unknown>>().notNull(),
    /** Endpoint fingerprints of the assertion the status rests on (endpoint_state compares against them). */
    fromFp: text(),
    toFp: text(),
    createdAt: createdAt(),
    updatedAt: timestamptz().notNull().defaultNow(),
  },
  (t) => [
    unique('relation_natural_key_unique').on(t.projectId, t.type, t.fromRef, t.toRef),
    unique('relation_project_id_unique').on(t.projectId, t.id),
    index('relation_from_model_idx').on(t.projectId, t.fromModel),
    index('relation_to_model_idx').on(t.projectId, t.toModel),
    check('relation_type_check', oneOf(t.type, RelationType.options)),
    check('relation_status_check', oneOf(t.status, RelationStatus.options)),
    check('relation_endpoint_state_check', oneOf(t.endpointState, EndpointState.options)),
    check('relation_tier_check', oneOf(t.tier, Tier.options)),
    check(
      'relation_confidence_check',
      sql`${t.confidence} is null or ${t.confidence} between 0 and 1`,
    ),
  ],
);

export const relationAssertion = pgTable(
  'relation_assertion',
  {
    id: text().primaryKey(),
    projectId: text().notNull(),
    relationId: text().notNull(),
    /** Seq of the event that recorded the assertion. */
    seq: seqColumn().notNull(),
    kind: text({ enum: ASSERTION_KINDS }).notNull(),
    verdict: text({ enum: VERDICTS }),
    /** Derived from the credential, never sent by clients (CONCEPT §6). */
    sourceKind: text({ enum: values(SourceKind.options) }).notNull(),
    principalId: text()
      .notNull()
      .references(() => principal.id),
    clientId: text(),
    /** Declared procedure and LLM model (agents). */
    declared: jsonb().$type<{ procedure: DeclaredProcedure | null; llmModel: string | null }>(),
    submissionId: text(),
    tier: text({ enum: values(Tier.options) }),
    confidence: doublePrecision(),
    /** Agent rationale, rejection reason, hold or accept note, or the text of a note. */
    rationale: text(),
    evidence: jsonb().$type<string[]>(),
    /** An agent's question to the reviewer, or the question of a hold. */
    question: text(),
    /** Label of a hold. */
    label: text(),
    /** `correct`: the manual relation accepted instead, or the corrected proposal. */
    linkedRelationId: text(),
    fromFp: text(),
    toFp: text(),
    /**
     * Basis of a pipeline proposal (judge each pair once): the `facts_hash`
     * of each endpoint's model as the judging agent saw it; null for every
     * other assertion and for proposals before procedure 0.2.0.
     */
    fromHash: text(),
    toHash: text(),
    /**
     * Auto-accept marker (owner decision 19): the rule and its revision that
     * recorded this human decision, and the agent proposal that triggered
     * it; a marked withdrawal is the decision's revocation (same rule and
     * revision, no trigger). Null on every other assertion.
     */
    autoAcceptRuleId: text(),
    autoAcceptRuleRevision: integer(),
    autoAcceptTriggerId: text(),
    createdAt: createdAt(),
  },
  (t): PgTableExtraConfigValue[] => [
    unique('relation_assertion_relation_id_unique').on(t.projectId, t.relationId, t.id),
    foreignKey({
      name: 'relation_assertion_relation_fk',
      columns: [t.projectId, t.relationId],
      foreignColumns: [relation.projectId, relation.id],
    }),
    foreignKey({
      name: 'relation_assertion_submission_fk',
      columns: [t.projectId, t.submissionId],
      foreignColumns: [analysisSubmission.projectId, analysisSubmission.id],
    }),
    // The decider is the author of the rule revision (MATCH SIMPLE: unmarked rows skip it).
    foreignKey({
      name: 'relation_assertion_auto_accept_rule_fk',
      columns: [t.projectId, t.autoAcceptRuleId, t.autoAcceptRuleRevision, t.principalId],
      foreignColumns: [
        autoAcceptRuleRevision.projectId,
        autoAcceptRuleRevision.ruleId,
        autoAcceptRuleRevision.revision,
        autoAcceptRuleRevision.principalId,
      ],
    }),
    // The trigger is an assertion of the same relation.
    foreignKey({
      name: 'relation_assertion_auto_accept_trigger_fk',
      columns: [t.projectId, t.relationId, t.autoAcceptTriggerId],
      foreignColumns: [t.projectId, t.relationId, t.id],
    }),
    index('relation_assertion_relation_idx').on(t.projectId, t.relationId, t.seq),
    index('relation_assertion_auto_accept_idx')
      .on(t.projectId, t.autoAcceptRuleId)
      .where(sql`${t.autoAcceptRuleId} is not null`),
    // Only a human acceptance with a trigger, or its revocation (a human withdrawal), is marked.
    check('relation_assertion_auto_accept_check', autoAcceptCheck(t)),
    // Agents only propose; humans (and the rule tier, for calls) decide.
    check(
      'relation_assertion_agents_never_decide',
      sql`not (${t.kind} = 'decision' and ${t.sourceKind} = 'agent')`,
    ),
    // Notes (answers to held questions) come from humans only.
    check(
      'relation_assertion_notes_by_humans',
      sql`${t.kind} <> 'note' or ${t.sourceKind} = 'human'`,
    ),
    check(
      'relation_assertion_verdict_check',
      sql`(${t.kind} = 'decision') = (${t.verdict} is not null) and (${t.verdict} is null or ${oneOf(t.verdict, VERDICTS)})`,
    ),
    check('relation_assertion_kind_check', oneOf(t.kind, ASSERTION_KINDS)),
    check('relation_assertion_source_kind_check', oneOf(t.sourceKind, SourceKind.options)),
    check(
      'relation_assertion_tier_check',
      sql`${t.tier} is null or ${oneOf(t.tier, Tier.options)}`,
    ),
    check(
      'relation_assertion_confidence_check',
      sql`${t.confidence} is null or ${t.confidence} between 0 and 1`,
    ),
  ],
);

/**
 * Analysis tasks (CONCEPT §3). The subject is a model revision
 * (`subject_kind = 'model'`, kind `relations`: `model_id`, `revision_id`,
 * `facts_hash`) or the value chain (`value_chain`, kind `placement`, M4 §8:
 * `value_chain_id`, `value_chain_revision_id` (the head at queue time, then
 * the head its claim showed), `input_hash` (digest of the processes due when
 * queued), `placement_claim`).
 */
export const analysisTask = pgTable(
  'analysis_task',
  {
    id: text().primaryKey(),
    projectId: text().notNull(),
    subjectKind: text({ enum: TASK_SUBJECT_KINDS }).notNull().default('model'),
    modelId: text(),
    revisionId: text(),
    valueChainId: text(),
    valueChainRevisionId: text(),
    kind: text({ enum: TASK_KINDS }).notNull(),
    /** `relations` tasks: the analysed revision's facts hash. */
    factsHash: text(),
    /** `placement` tasks: digest of the due processes and their input hashes when queued. */
    inputHash: text(),
    state: text({ enum: TASK_STATES }).notNull(),
    leaseTokenHash: text(),
    claimedBy: text().references(() => principal.id),
    leaseUntil: timestamptz(),
    attempts: integer().notNull().default(0),
    lastError: text(),
    /** Seq of the latest `analysis.claimed` event: the project state the claim input shows. */
    claimedSeq: seqColumn(),
    /**
     * The typed pairs the latest claim must judge (its candidates minus
     * judged and skipped pairs); cleared when the task leaves `claimed`
     * without a submission.
     */
    assignment: jsonb().$type<TypedPair[]>(),
    /**
     * A judgement this claim relied on was withdrawn (relations), or the chain or
     * the models changed during the lease (placement): its submit queues a follow-up task.
     */
    requeueAfter: boolean().notNull().default(false),
    /** `placement` tasks: what the latest claim showed; cleared when the task leaves `claimed` unsubmitted. */
    placementClaim: jsonb().$type<PlacementClaim>(),
    /** Seq of the `analysis.queued` event; orders tasks of a model (created_at ties within a transaction). */
    seq: seqColumn().notNull(),
    createdAt: createdAt(),
    updatedAt: timestamptz().notNull().defaultNow(),
  },
  (t): PgTableExtraConfigValue[] => [
    unique('analysis_task_project_id_unique').on(t.projectId, t.id),
    foreignKey({
      name: 'analysis_task_model_fk',
      columns: [t.projectId, t.modelId],
      foreignColumns: [model.projectId, model.id],
    }),
    foreignKey({
      name: 'analysis_task_revision_fk',
      columns: [t.projectId, t.revisionId],
      foreignColumns: [modelRevision.projectId, modelRevision.id],
    }),
    foreignKey({
      name: 'analysis_task_value_chain_fk',
      columns: [t.projectId, t.valueChainId],
      foreignColumns: [valueChain.projectId, valueChain.id],
    }),
    // The revision belongs to the task's chain.
    foreignKey({
      name: 'analysis_task_value_chain_revision_fk',
      columns: [t.projectId, t.valueChainId, t.valueChainRevisionId],
      foreignColumns: [
        valueChainRevision.projectId,
        valueChainRevision.valueChainId,
        valueChainRevision.id,
      ],
    }),
    // One open task per model and kind (CONCEPT §2) …
    uniqueIndex('analysis_task_open_unique')
      .on(t.modelId, t.kind)
      .where(sql`${t.state} in ('queued', 'claimed') and ${t.subjectKind} = 'model'`),
    // … and per value chain and kind (M4 §3.2: no two placement claims ever coexist).
    uniqueIndex('analysis_task_open_chain_unique')
      .on(t.valueChainId, t.kind)
      .where(sql`${t.state} in ('queued', 'claimed') and ${t.subjectKind} = 'value_chain'`),
    index('analysis_task_model_idx').on(t.projectId, t.modelId, t.kind, t.seq),
    index('analysis_task_chain_idx').on(t.projectId, t.valueChainId, t.kind, t.seq),
    index('analysis_task_state_idx').on(t.state, t.createdAt),
    check('analysis_task_kind_check', oneOf(t.kind, TASK_KINDS)),
    check('analysis_task_state_check', oneOf(t.state, TASK_STATES)),
    check('analysis_task_subject_kind_check', oneOf(t.subjectKind, TASK_SUBJECT_KINDS)),
    // The subject's columns, and only those (M4 §8).
    check(
      'analysis_task_subject_check',
      sql`(${t.subjectKind} = 'model' and ${t.modelId} is not null and ${t.revisionId} is not null and ${t.factsHash} is not null and ${t.valueChainId} is null and ${t.valueChainRevisionId} is null and ${t.inputHash} is null and ${t.placementClaim} is null) or (${t.subjectKind} = 'value_chain' and ${t.valueChainId} is not null and ${t.valueChainRevisionId} is not null and ${t.inputHash} is not null and ${t.modelId} is null and ${t.revisionId} is null and ${t.factsHash} is null and ${t.assignment} is null)`,
    ),
    // Relations tasks analyse models, placement tasks the value chain.
    check(
      'analysis_task_kind_subject_check',
      sql`(${t.kind} = 'relations') = (${t.subjectKind} = 'model')`,
    ),
  ],
);

/** Submissions, stored verbatim for the eval (CONCEPT §3, §7). */
export const analysisSubmission = pgTable(
  'analysis_submission',
  {
    id: text().primaryKey(),
    projectId: text().notNull(),
    taskId: text().notNull().unique('analysis_submission_task_unique'),
    /** Client-chosen `submissionId` (UUID); replays return the stored result. */
    clientSubmissionId: text().notNull(),
    principalId: text()
      .notNull()
      .references(() => principal.id),
    /** Client of the credential (`agt_…`, `proa-web`, `proa-cli`). */
    clientId: text(),
    declared: jsonb().$type<{ procedure: DeclaredProcedure; llmModel: string | null }>().notNull(),
    /** The request as received, minus the lease token. */
    payload: jsonb().$type<Record<string, unknown>>().notNull(),
    result: jsonb().$type<AnalysisSubmissionResult>().notNull(),
    seq: seqColumn().notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    unique('analysis_submission_project_id_unique').on(t.projectId, t.id),
    foreignKey({
      name: 'analysis_submission_task_fk',
      columns: [t.projectId, t.taskId],
      foreignColumns: [analysisTask.projectId, analysisTask.id],
    }),
  ],
);

/**
 * No-links (judge each pair once): an agent's judgement that a typed pair is
 * unrelated, stored from a submission with its basis (the `facts_hash` of
 * both endpoint models as the agent saw them). Append-only; live while it
 * has no `no_link_withdrawal` row.
 */
export const noLink = pgTable(
  'no_link',
  {
    id: text().primaryKey(),
    projectId: text().notNull(),
    type: text({ enum: LINK_TYPES }).notNull(),
    fromRef: text().notNull(),
    toRef: text().notNull(),
    /** Model keys of both endpoints (set on insert). */
    fromModel: text().notNull(),
    toModel: text().notNull(),
    fromHash: text().notNull(),
    toHash: text().notNull(),
    reason: text().notNull(),
    /** Derived from the credential (CONCEPT §6). */
    sourceKind: text({ enum: JUDGING_SOURCE_KINDS }).notNull(),
    principalId: text()
      .notNull()
      .references(() => principal.id),
    clientId: text(),
    declared: jsonb().$type<{ procedure: DeclaredProcedure; llmModel: string | null }>().notNull(),
    submissionId: text().notNull(),
    /** The analysed model (origin). */
    modelId: text().notNull(),
    /** Seq of the submission's `analysis.done` event. */
    seq: seqColumn().notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    unique('no_link_project_id_unique').on(t.projectId, t.id),
    unique('no_link_submission_pair_unique').on(t.submissionId, t.type, t.fromRef, t.toRef),
    foreignKey({
      name: 'no_link_submission_fk',
      columns: [t.projectId, t.submissionId],
      foreignColumns: [analysisSubmission.projectId, analysisSubmission.id],
    }),
    foreignKey({
      name: 'no_link_model_fk',
      columns: [t.projectId, t.modelId],
      foreignColumns: [model.projectId, model.id],
    }),
    index('no_link_from_model_idx').on(t.projectId, t.fromModel),
    index('no_link_to_model_idx').on(t.projectId, t.toModel),
    index('no_link_pair_idx').on(t.projectId, t.fromRef, t.toRef),
    index('no_link_principal_idx').on(t.projectId, t.principalId),
    check('no_link_type_check', oneOf(t.type, LINK_TYPES)),
    check('no_link_source_kind_check', oneOf(t.sourceKind, JUDGING_SOURCE_KINDS)),
  ],
);

/** The end of a no-link (supersession, replacement, token revocation); append-only. */
export const noLinkWithdrawal = pgTable(
  'no_link_withdrawal',
  {
    noLinkId: text()
      .primaryKey()
      .references(() => noLink.id),
    projectId: text().notNull(),
    /** Seq of the event that caused it (`analysis.done`, `agent_token.revoked`). */
    seq: seqColumn().notNull(),
    /** Who caused it. */
    principalId: text()
      .notNull()
      .references(() => principal.id),
    reason: text().notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    foreignKey({
      name: 'no_link_withdrawal_project_fk',
      columns: [t.projectId, t.noLinkId],
      foreignColumns: [noLink.projectId, noLink.id],
    }),
  ],
);

/**
 * A value chain (M4 §2): the project's process landscape map. Mutable like
 * `model`; M4 allows one chain per project, key `main` (the domain enforces
 * it, so more chains need no migration). A deleted chain keeps its id, and
 * re-creating it revives that row.
 */
export const valueChain = pgTable(
  'value_chain',
  {
    id: text().primaryKey(),
    projectId: text()
      .notNull()
      .references(() => project.id),
    /** Immutable key (`main` in M4). */
    key: text().notNull(),
    /** `meta.name` of the head revision. */
    name: text().notNull(),
    /** Null only inside the transaction that creates the chain. */
    headRevisionId: text(),
    /** Set while the chain is deleted (seq of `value_chain.deleted`). */
    deletedSeq: seqColumn(),
    createdAt: createdAt(),
    updatedAt: timestamptz().notNull().defaultNow(),
  },
  (t): PgTableExtraConfigValue[] => [
    unique('value_chain_project_key_unique').on(t.projectId, t.key),
    unique('value_chain_project_id_unique').on(t.projectId, t.id),
    // The head is a revision of this chain.
    foreignKey({
      name: 'value_chain_head_revision_fk',
      columns: [t.projectId, t.id, t.headRevisionId],
      foreignColumns: [
        valueChainRevision.projectId,
        valueChainRevision.valueChainId,
        valueChainRevision.id,
      ],
    }),
  ],
);

/** A saved state of a value chain (M4 §2); append-only, always saved by a human. */
export const valueChainRevision = pgTable(
  'value_chain_revision',
  {
    id: text().primaryKey(),
    projectId: text().notNull(),
    valueChainId: text().notNull(),
    /** 1, 2, …; continues after a deletion and revival, so `"r<rev>"` never repeats. */
    rev: integer().notNull(),
    /** Canonical bytes: UTF-8 of `serializeDocument(loadDocument(input))`. */
    content: bytea().notNull(),
    /** sha256 (hex) of `content`: an identical save is a no-op. */
    contentHash: text().notNull(),
    /** Ids, types, names, links, connections and step kinds; not geometry (M4 §2). */
    structureHash: text().notNull(),
    schemaVersion: integer().notNull(),
    /** The revision the editor started from (`If-Match`). */
    baseRevisionId: text(),
    principalId: text()
      .notNull()
      .references(() => principal.id),
    /** Derived from the credential; humans only (check). */
    sourceKind: text({ enum: values(SourceKind.options) }).notNull(),
    seq: seqColumn().notNull(),
    createdAt: createdAt(),
  },
  (t): PgTableExtraConfigValue[] => [
    unique('value_chain_revision_project_id_unique').on(t.projectId, t.id),
    unique('value_chain_revision_chain_id_unique').on(t.projectId, t.valueChainId, t.id),
    unique('value_chain_revision_chain_rev_unique').on(t.valueChainId, t.rev),
    foreignKey({
      name: 'value_chain_revision_chain_fk',
      columns: [t.projectId, t.valueChainId],
      foreignColumns: [valueChain.projectId, valueChain.id],
    }),
    foreignKey({
      name: 'value_chain_revision_base_fk',
      columns: [t.projectId, t.valueChainId, t.baseRevisionId],
      foreignColumns: [t.projectId, t.valueChainId, t.id],
    }),
    // Agents never edit the chain (M4 §7).
    check('value_chain_revision_humans_only', sql`${t.sourceKind} = 'human'`),
    check('value_chain_revision_rev_check', sql`${t.rev} >= 1`),
    check('value_chain_revision_schema_version_check', sql`${t.schemaVersion} >= 1`),
  ],
);

/**
 * Generations of the chain's steps (M4 §2 "Identity"): one row per element
 * id of type `step` and generation, plus the pseudo-step `@outside`. A step
 * removed from the head is tombstoned (`deleted_seq`); if its id reappears it
 * is a new generation, so placements of the old one stay `missing`. Rows only
 * ever take their tombstone (trigger in 0007).
 */
export const valueChainStep = pgTable(
  'value_chain_step',
  {
    projectId: text().notNull(),
    valueChainId: text().notNull(),
    elementId: text().notNull(),
    generation: integer().notNull(),
    /** The revision that added this generation. */
    createdRev: integer().notNull(),
    /** The first revision without it; null while live and when the chain's deletion ended it. */
    deletedRev: integer(),
    /** The tombstone: seq of the `value_chain.revised` or `value_chain.deleted` event. */
    deletedSeq: seqColumn(),
  },
  (t): PgTableExtraConfigValue[] => [
    primaryKey({ columns: [t.valueChainId, t.elementId, t.generation] }),
    unique('value_chain_step_project_key_unique').on(
      t.projectId,
      t.valueChainId,
      t.elementId,
      t.generation,
    ),
    foreignKey({
      name: 'value_chain_step_chain_fk',
      columns: [t.projectId, t.valueChainId],
      foreignColumns: [valueChain.projectId, valueChain.id],
    }),
    foreignKey({
      name: 'value_chain_step_created_rev_fk',
      columns: [t.valueChainId, t.createdRev],
      foreignColumns: [valueChainRevision.valueChainId, valueChainRevision.rev],
    }),
    foreignKey({
      name: 'value_chain_step_deleted_rev_fk',
      columns: [t.valueChainId, t.deletedRev],
      foreignColumns: [valueChainRevision.valueChainId, valueChainRevision.rev],
    }),
    // One live generation per element id.
    uniqueIndex('value_chain_step_live_unique')
      .on(t.valueChainId, t.elementId)
      .where(sql`${t.deletedSeq} is null`),
    check('value_chain_step_generation_check', sql`${t.generation} >= 1`),
    check(
      'value_chain_step_tombstone_check',
      sql`(${t.deletedRev} is null or ${t.deletedSeq} is not null) and (${t.deletedRev} is null or ${t.deletedRev} > ${t.createdRev})`,
    ),
  ],
);

/**
 * A placement (M4 §2): a process belongs to a step generation (or to
 * `@outside`). Mutable derived state like `relation`; its history is in
 * `placement_assertion`.
 */
export const placement = pgTable(
  'placement',
  {
    id: text().primaryKey(),
    projectId: text()
      .notNull()
      .references(() => project.id),
    valueChainId: text().notNull(),
    elementId: text().notNull(),
    generation: integer().notNull(),
    /** `<model_key>#<process_id>`. */
    processRef: text().notNull(),
    /** Model key of the process, for "placements touching model M". */
    processModel: text()
      .notNull()
      .generatedAlwaysAs(sql`split_part(process_ref, '#', 1)`),
    status: text({ enum: values(RelationStatus.options) }).notNull(),
    endpointState: text({ enum: values(EndpointState.options) }).notNull(),
    tier: text({ enum: PLACEMENT_TIERS }).notNull(),
    confidence: doublePrecision(),
    /** Incremented on every change (optimistic concurrency for decisions). */
    version: integer().notNull().default(1),
    /** Fingerprints of the assertion the status rests on (endpoint state compares against them). */
    stepFp: text(),
    processFp: text(),
    createdAt: createdAt(),
    updatedAt: timestamptz().notNull().defaultNow(),
  },
  (t): PgTableExtraConfigValue[] => [
    unique('placement_natural_key_unique').on(
      t.projectId,
      t.valueChainId,
      t.elementId,
      t.generation,
      t.processRef,
    ),
    unique('placement_project_id_unique').on(t.projectId, t.id),
    // Pins the chain and the project too; `@outside` has its own step row.
    foreignKey({
      name: 'placement_step_fk',
      columns: [t.projectId, t.valueChainId, t.elementId, t.generation],
      foreignColumns: [
        valueChainStep.projectId,
        valueChainStep.valueChainId,
        valueChainStep.elementId,
        valueChainStep.generation,
      ],
    }),
    index('placement_process_model_idx').on(t.projectId, t.processModel),
    index('placement_process_idx').on(t.projectId, t.valueChainId, t.processRef),
    check('placement_status_check', oneOf(t.status, RelationStatus.options)),
    check('placement_endpoint_state_check', oneOf(t.endpointState, EndpointState.options)),
    check('placement_tier_check', oneOf(t.tier, PLACEMENT_TIERS)),
    check(
      'placement_confidence_check',
      sql`${t.confidence} is null or ${t.confidence} between 0 and 1`,
    ),
    check('placement_generation_check', sql`${t.generation} >= 1`),
  ],
);

/** The history of a placement (M4 §2); append-only, mirrors `relation_assertion`. */
export const placementAssertion = pgTable(
  'placement_assertion',
  {
    id: text().primaryKey(),
    projectId: text().notNull(),
    placementId: text().notNull(),
    /** Seq of the event that recorded the assertion. */
    seq: seqColumn().notNull(),
    kind: text({ enum: ASSERTION_KINDS }).notNull(),
    verdict: text({ enum: VERDICTS }),
    /** Derived from the credential, never sent by clients (CONCEPT §6). */
    sourceKind: text({ enum: values(SourceKind.options) }).notNull(),
    principalId: text()
      .notNull()
      .references(() => principal.id),
    clientId: text(),
    /** Declared procedure and LLM model (agents). */
    declared: jsonb().$type<{ procedure: DeclaredProcedure | null; llmModel: string | null }>(),
    /** The stored submission of a pipeline proposal (M4b). */
    submissionId: text(),
    tier: text({ enum: PLACEMENT_TIERS }),
    confidence: doublePrecision(),
    /** Agent rationale (required for `@outside`), rejection reason, hold or accept note, or a note. */
    rationale: text(),
    evidence: jsonb().$type<string[]>(),
    /** An agent's question to the reviewer, or the question of a hold. */
    question: text(),
    /** Label of a hold. */
    label: text(),
    /** `correct`: the manual placement accepted instead, or the corrected placement. */
    linkedPlacementId: text(),
    stepFp: text(),
    processFp: text(),
    /**
     * Basis of a pipeline proposal (M4b, judge each subject once): digests of
     * what the claim showed of the chain's steps and of the process
     * (`chainInputDigest`, `processInputDigest`); null for every other
     * assertion.
     */
    stepHash: text(),
    processHash: text(),
    /** Auto-accept marker (owner decision 19), as on `relation_assertion`. */
    autoAcceptRuleId: text(),
    autoAcceptRuleRevision: integer(),
    autoAcceptTriggerId: text(),
    createdAt: createdAt(),
  },
  (t): PgTableExtraConfigValue[] => [
    unique('placement_assertion_placement_id_unique').on(t.projectId, t.placementId, t.id),
    foreignKey({
      name: 'placement_assertion_placement_fk',
      columns: [t.projectId, t.placementId],
      foreignColumns: [placement.projectId, placement.id],
    }),
    foreignKey({
      name: 'placement_assertion_linked_fk',
      columns: [t.projectId, t.linkedPlacementId],
      foreignColumns: [placement.projectId, placement.id],
    }),
    // Made DEFERRABLE INITIALLY DEFERRED in 0007 (as 0003 did for relation assertions).
    foreignKey({
      name: 'placement_assertion_submission_fk',
      columns: [t.projectId, t.submissionId],
      foreignColumns: [analysisSubmission.projectId, analysisSubmission.id],
    }),
    // The decider is the author of the rule revision (MATCH SIMPLE: unmarked rows skip it).
    foreignKey({
      name: 'placement_assertion_auto_accept_rule_fk',
      columns: [t.projectId, t.autoAcceptRuleId, t.autoAcceptRuleRevision, t.principalId],
      foreignColumns: [
        autoAcceptRuleRevision.projectId,
        autoAcceptRuleRevision.ruleId,
        autoAcceptRuleRevision.revision,
        autoAcceptRuleRevision.principalId,
      ],
    }),
    // The trigger is an assertion of the same placement.
    foreignKey({
      name: 'placement_assertion_auto_accept_trigger_fk',
      columns: [t.projectId, t.placementId, t.autoAcceptTriggerId],
      foreignColumns: [t.projectId, t.placementId, t.id],
    }),
    index('placement_assertion_placement_idx').on(t.projectId, t.placementId, t.seq),
    index('placement_assertion_auto_accept_idx')
      .on(t.projectId, t.autoAcceptRuleId)
      .where(sql`${t.autoAcceptRuleId} is not null`),
    check('placement_assertion_auto_accept_check', autoAcceptCheck(t)),
    // Agents only propose; humans decide (M4 §7).
    check(
      'placement_assertion_agents_never_decide',
      sql`not (${t.kind} = 'decision' and ${t.sourceKind} = 'agent')`,
    ),
    // The rule tier only proposes (M4 §2 "Tiers"); an owner's auto-accept rule records a
    // human decision (owner decision 19), never a `rule` one.
    check(
      'placement_assertion_rules_never_decide',
      sql`not (${t.kind} = 'decision' and ${t.sourceKind} = 'rule')`,
    ),
    check(
      'placement_assertion_notes_by_humans',
      sql`${t.kind} <> 'note' or ${t.sourceKind} = 'human'`,
    ),
    check(
      'placement_assertion_verdict_check',
      sql`(${t.kind} = 'decision') = (${t.verdict} is not null) and (${t.verdict} is null or ${oneOf(t.verdict, VERDICTS)})`,
    ),
    check('placement_assertion_kind_check', oneOf(t.kind, ASSERTION_KINDS)),
    check('placement_assertion_source_kind_check', oneOf(t.sourceKind, SourceKind.options)),
    check(
      'placement_assertion_tier_check',
      sql`${t.tier} is null or ${oneOf(t.tier, PLACEMENT_TIERS)}`,
    ),
    check(
      'placement_assertion_confidence_check',
      sql`${t.confidence} is null or ${t.confidence} between 0 and 1`,
    ),
    // A basis has both hashes, and only proposals carry one.
    check(
      'placement_assertion_basis_check',
      sql`(${t.stepHash} is null) = (${t.processHash} is null) and (${t.stepHash} is null or ${t.kind} = 'proposal')`,
    ),
  ],
);

/**
 * The agent's last verdict per process and chain (M4 §3.2, judge each process
 * once): the process's input hash when it was judged, and the outcome
 * (`proposed`, `unsure` with the reason, or `skipped`). A process is offered
 * to a placement task again only when its current input hash differs. Written
 * by placement submissions (`task_id` set) and by agents' ad-hoc proposals
 * (`task_id` null); deleted when the judgement is lost (a revoked token, a
 * withdrawn pipeline proposal). Mutable memory, not history.
 */
export const placementInput = pgTable(
  'placement_input',
  {
    projectId: text().notNull(),
    valueChainId: text().notNull(),
    /** `<model_key>#<process_id>`. */
    processRef: text().notNull(),
    inputHash: text().notNull(),
    /** The placement task whose submission wrote it; null for an ad-hoc proposal. */
    taskId: text(),
    /** The judging agent. */
    principalId: text()
      .notNull()
      .references(() => principal.id),
    outcome: text({ enum: PLACEMENT_INPUT_OUTCOMES }).notNull(),
    /** The agent's reason, for `unsure` only. */
    reason: text(),
    /** Seq of the event of the write (the submission's `analysis.done`, else the project's last). */
    seq: seqColumn().notNull(),
    createdAt: createdAt(),
    updatedAt: timestamptz().notNull().defaultNow(),
  },
  (t): PgTableExtraConfigValue[] => [
    primaryKey({ columns: [t.valueChainId, t.processRef] }),
    foreignKey({
      name: 'placement_input_chain_fk',
      columns: [t.projectId, t.valueChainId],
      foreignColumns: [valueChain.projectId, valueChain.id],
    }),
    foreignKey({
      name: 'placement_input_task_fk',
      columns: [t.projectId, t.taskId],
      foreignColumns: [analysisTask.projectId, analysisTask.id],
    }),
    check('placement_input_outcome_check', oneOf(t.outcome, PLACEMENT_INPUT_OUTCOMES)),
    check(
      'placement_input_reason_check',
      sql`(${t.outcome} = 'unsure') = (${t.reason} is not null)`,
    ),
  ],
);

/**
 * An owner's auto-accept rule (owner decision 19): the immutable head row
 * (id, kind, creator). What it matches lives in its revisions. Never deleted
 * (a rule is disabled instead), so decisions always resolve their rule;
 * append-only (trigger in 0010).
 */
export const autoAcceptRule = pgTable(
  'auto_accept_rule',
  {
    id: text().primaryKey(),
    projectId: text()
      .notNull()
      .references(() => project.id),
    kind: text({ enum: AUTO_ACCEPT_KINDS }).notNull(),
    createdBy: text()
      .notNull()
      .references(() => principal.id),
    /** Seq of `auto_accept_rule.created`: the creation order (the first matching rule wins). */
    seq: seqColumn().notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    unique('auto_accept_rule_project_id_unique').on(t.projectId, t.id),
    unique('auto_accept_rule_project_id_kind_unique').on(t.projectId, t.id, t.kind),
    check('auto_accept_rule_kind_check', oneOf(t.kind, AUTO_ACCEPT_KINDS)),
  ],
);

/**
 * A revision of an auto-accept rule: every create, edit, enable and disable
 * appends one, written by a human owner; the head is the highest revision.
 * Decisions reference the revision they were recorded under, together with
 * its author (their principal, pinned by the assertions' composite foreign
 * key). Append-only (trigger in 0010).
 */
export const autoAcceptRuleRevision = pgTable(
  'auto_accept_rule_revision',
  {
    projectId: text().notNull(),
    ruleId: text().notNull(),
    /** The rule's kind (fixed; repeated for the kind and tier check). */
    kind: text({ enum: AUTO_ACCEPT_KINDS }).notNull(),
    revision: integer().notNull(),
    name: text().notNull(),
    enabled: boolean().notNull(),
    tier: text({ enum: AUTO_ACCEPT_TIERS }).notNull(),
    /** Inclusive minimum confidence, 0.5 to 1. */
    minConfidence: doublePrecision().notNull(),
    note: text(),
    /** Relations only: accept only this type. */
    relationType: text({ enum: LINK_TYPES }),
    /** Only proposals of this principal. */
    agentPrincipalId: text().references(() => principal.id),
    /** Only proposals declaring exactly this LLM model. */
    llmModel: text(),
    /** Also ad-hoc proposals (default: pipeline proposals only). */
    includeAdHoc: boolean().notNull().default(false),
    /** The author: decisions of this revision are recorded under this principal. */
    principalId: text()
      .notNull()
      .references(() => principal.id),
    clientId: text(),
    /** Derived from the credential; humans only (check). */
    sourceKind: text({ enum: values(SourceKind.options) }).notNull(),
    /** Seq of the `auto_accept_rule.created` or `.revised` event. */
    seq: seqColumn().notNull(),
    createdAt: createdAt(),
  },
  (t): PgTableExtraConfigValue[] => [
    primaryKey({ columns: [t.ruleId, t.revision] }),
    unique('auto_accept_rule_revision_project_unique').on(t.projectId, t.ruleId, t.revision),
    // Target of the assertions' marker: pins the deciding principal to the author.
    unique('auto_accept_rule_revision_author_unique').on(
      t.projectId,
      t.ruleId,
      t.revision,
      t.principalId,
    ),
    foreignKey({
      name: 'auto_accept_rule_revision_rule_fk',
      columns: [t.projectId, t.ruleId, t.kind],
      foreignColumns: [autoAcceptRule.projectId, autoAcceptRule.id, autoAcceptRule.kind],
    }),
    // Only humans write rules; agents can neither create nor change them.
    check('auto_accept_rule_revision_humans_only', sql`${t.sourceKind} = 'human'`),
    check('auto_accept_rule_revision_revision_check', sql`${t.revision} >= 1`),
    check('auto_accept_rule_revision_confidence_check', sql`${t.minConfidence} between 0.5 and 1`),
    check(
      'auto_accept_rule_revision_tier_check',
      sql`(${t.kind} = 'relation' and ${oneOf(t.tier, ['key', 'lexical', 'semantic'])}) or (${t.kind} = 'placement' and ${oneOf(t.tier, ['lexical', 'semantic'])} and ${t.relationType} is null)`,
    ),
    check(
      'auto_accept_rule_revision_type_check',
      sql`${t.relationType} is null or ${oneOf(t.relationType, LINK_TYPES)}`,
    ),
    check('auto_accept_rule_revision_kind_check', oneOf(t.kind, AUTO_ACCEPT_KINDS)),
    check(
      'auto_accept_rule_revision_name_check',
      sql`char_length(${t.name}) between 1 and 100 and (${t.llmModel} is null or char_length(${t.llmModel}) between 1 and 100)`,
    ),
  ],
);

/** Change feed and audit log; append-only (trigger). */
export const event = pgTable(
  'event',
  {
    projectId: text()
      .notNull()
      .references(() => project.id),
    seq: seqColumn().notNull(),
    type: text().notNull(),
    principalId: text()
      .notNull()
      .references(() => principal.id),
    clientId: text(),
    subjectRef: text(),
    payload: jsonb().$type<Record<string, unknown>>().notNull(),
    at: timestamptz().notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.projectId, t.seq] })],
);

/**
 * Deterministic findings of the project head, recomputed by every ingest and
 * delete (derived state, replaced as a whole; not part of the history).
 */
export const finding = pgTable(
  'finding',
  {
    projectId: text()
      .notNull()
      .references(() => project.id),
    ord: integer().notNull(),
    kind: text({ enum: values(FindingKind.options) }).notNull(),
    refs: text().array().notNull(),
    detail: text().notNull(),
  },
  (t) => [
    primaryKey({ columns: [t.projectId, t.ord] }),
    check('finding_kind_check', oneOf(t.kind, FindingKind.options)),
  ],
);

/**
 * `model_pipeline` (CONCEPT §3): stage and open items per live model.
 * Stage from the latest non-cancelled `relations` task: queued →
 * waiting_for_agent, claimed → agent_working, failed → agent_failed, done →
 * waiting_for_review (any proposed item, or an accepted relation whose
 * endpoint is not ok), waiting_for_clarification (only held items),
 * incorporated. Open items: relations touching the model that are proposed,
 * held, or accepted with endpoint_state ≠ ok.
 */
export const modelPipeline = pgView('model_pipeline', {
  projectId: text('project_id').notNull(),
  modelId: text('model_id').notNull(),
  modelKey: text('model_key').notNull(),
  taskState: text('task_state', { enum: TASK_STATES }),
  reviewItems: integer('review_items').notNull(),
  heldItems: integer('held_items').notNull(),
  openItems: integer('open_items').notNull(),
  stage: text('stage').notNull(),
}).as(sql`
  select m.project_id, m.id as model_id, m.key as model_key, t.state as task_state,
         r.review_items, r.held_items, r.review_items + r.held_items as open_items,
         case
           when t.state = 'claimed' then 'agent_working'
           when t.state = 'failed' then 'agent_failed'
           when t.state = 'done' then case
             when r.review_items > 0 then 'waiting_for_review'
             when r.held_items > 0 then 'waiting_for_clarification'
             else 'incorporated' end
           else 'waiting_for_agent'
         end as stage
  from model m
  left join lateral (
    select a.state from analysis_task a
    where a.project_id = m.project_id and a.model_id = m.id
      and a.kind = 'relations' and a.state <> 'cancelled'
    order by a.seq desc
    limit 1
  ) t on true
  cross join lateral (
    select
      (count(*) filter (where x.status = 'proposed'
        or (x.status = 'accepted' and x.endpoint_state <> 'ok')))::int as review_items,
      (count(*) filter (where x.status = 'held'))::int as held_items
    from relation x
    where x.project_id = m.project_id and (x.from_model = m.key or x.to_model = m.key)
  ) r
  where m.deleted_seq is null
`);

/**
 * `value_chain_pipeline` (M4 §3.5): the stage of each live chain's
 * `placement` pipeline, mapped as CONCEPT §3 maps a model's. From the latest
 * non-cancelled placement task: claimed → agent_working, failed →
 * agent_failed, queued → waiting_for_agent; done, or no task yet (a chain
 * created before M4b, or nothing ever due), → waiting_for_review (any review
 * item), waiting_for_clarification (only held items), incorporated. Review
 * items: proposed placements on a live step generation and accepted ones
 * whose endpoint is not ok (the page's open items); held items: held
 * placements.
 */
export const valueChainPipeline = pgView('value_chain_pipeline', {
  projectId: text('project_id').notNull(),
  valueChainId: text('value_chain_id').notNull(),
  taskId: text('task_id'),
  taskState: text('task_state', { enum: TASK_STATES }),
  reviewItems: integer('review_items').notNull(),
  heldItems: integer('held_items').notNull(),
  stage: text('stage').notNull(),
}).as(sql`
  select c.project_id, c.id as value_chain_id, t.id as task_id, t.state as task_state,
         i.review_items, i.held_items,
         case
           when t.state = 'claimed' then 'agent_working'
           when t.state = 'failed' then 'agent_failed'
           when t.state = 'queued' then 'waiting_for_agent'
           when i.review_items > 0 then 'waiting_for_review'
           when i.held_items > 0 then 'waiting_for_clarification'
           else 'incorporated'
         end as stage
  from value_chain c
  left join lateral (
    select a.id, a.state from analysis_task a
    where a.project_id = c.project_id and a.value_chain_id = c.id
      and a.kind = 'placement' and a.state <> 'cancelled'
    order by a.seq desc
    limit 1
  ) t on true
  cross join lateral (
    select
      (count(*) filter (where (x.status = 'proposed' and s.deleted_seq is null)
        or (x.status = 'accepted' and x.endpoint_state <> 'ok')))::int as review_items,
      (count(*) filter (where x.status = 'held'))::int as held_items
    from placement x
    join value_chain_step s on s.value_chain_id = x.value_chain_id
      and s.element_id = x.element_id and s.generation = x.generation
    where x.project_id = c.project_id and x.value_chain_id = c.id
  ) i
  where c.deleted_seq is null
`);
