/**
 * Drizzle schema (CONCEPT §2, "PostgreSQL sketch"). Conventions:
 * - camelCase keys in TypeScript, snake_case columns (`casing: 'snake_case'`
 *   in drizzle.config.ts and in `createDatabase`);
 * - ids are typed ULIDs (`prj_…`) in `text` columns, generated by the domain;
 * - child rows carry `project_id` with composite foreign keys
 *   `(project_id, x_id) → parent(project_id, id)`, so a row can never point
 *   into another project;
 * - enumerations are `text` plus a CHECK constraint (no Postgres enums, which
 *   are awkward to migrate);
 * - `event`, `relation_assertion`, `analysis_submission`, `no_link` and
 *   `no_link_withdrawal` are append-only (triggers in migrations
 *   0001_append_only.sql and 0005_judge_once_triggers.sql).
 *
 * After changing this file run `pnpm --filter @proa/server db:generate` and
 * commit the new migration in `apps/server/drizzle/`.
 */
import {
  AgentScope,
  AssertionKind,
  Engine,
  EndpointState,
  EventDef,
  FactKind,
  FactScope,
  FindingKind,
  RelationStatus,
  RelationType,
  Role,
  SourceKind,
  Tier,
  type DeclaredProcedure,
  type FactAttrs,
  type MessageFlowInfo,
  type ProcessInfo,
  type RevisionSource,
  type SubmissionResult,
  type TypedPair,
} from '@proa/contracts';
import { sql, type SQL } from 'drizzle-orm';
import {
  bigint,
  boolean,
  check,
  customType,
  doublePrecision,
  foreignKey,
  index,
  integer,
  jsonb,
  pgTable,
  pgView,
  primaryKey,
  text,
  timestamp,
  unique,
  uniqueIndex,
  type AnyPgColumn,
  type PgTableExtraConfigValue,
} from 'drizzle-orm/pg-core';

/** Raw bytes (`bytea`); revisions keep the uploaded BPMN verbatim. */
const bytea = customType<{ data: Uint8Array; driverData: Buffer }>({
  dataType: () => 'bytea',
  toDriver: (value) => Buffer.from(value.buffer, value.byteOffset, value.byteLength),
  fromDriver: (value) => new Uint8Array(value.buffer, value.byteOffset, value.byteLength),
});

const timestamptz = () => timestamp({ withTimezone: true, mode: 'date' });
const createdAt = () => timestamptz().notNull().defaultNow();
/** Event sequence numbers (`project.last_seq`); bigint, read as number (< 2^53). */
const seqColumn = () => bigint({ mode: 'number' });

/** zod enum options as the non-empty tuple drizzle's `text({ enum })` wants. */
function values<T extends string>(options: readonly T[]): readonly [T, ...T[]] {
  return options as unknown as readonly [T, ...T[]];
}

/** `col in ('a', 'b')` for CHECK constraints. Values are code constants, never user input. */
function oneOf(column: AnyPgColumn, values: readonly string[]): SQL {
  const list = values.map((v) => `'${v.replaceAll("'", "''")}'`).join(', ');
  return sql`${column} in (${sql.raw(list)})`;
}

export const PRINCIPAL_KINDS = ['user', 'service', 'system'] as const;
export const ASSERTION_KINDS = values(AssertionKind.options);
export const VERDICTS = ['accept', 'reject', 'hold'] as const;
export const TASK_KINDS = ['relations'] as const;
export const TASK_STATES = ['queued', 'claimed', 'done', 'failed', 'cancelled'] as const;
export const LINK_TYPES = ['call', 'message', 'signal', 'trigger'] as const;
export const JUDGING_SOURCE_KINDS = ['agent', 'human'] as const;

export const project = pgTable('project', {
  id: text().primaryKey(),
  key: text().notNull().unique(),
  name: text().notNull(),
  /** Last allocated event sequence number (`UPDATE … SET last_seq = last_seq + 1 RETURNING`). */
  lastSeq: seqColumn().notNull().default(0),
  createdAt: createdAt(),
});

export const principal = pgTable(
  'principal',
  {
    id: text().primaryKey(),
    kind: text({ enum: PRINCIPAL_KINDS }).notNull(),
    iss: text().notNull(),
    subject: text().notNull(),
    email: text(),
    handle: text().notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    unique('principal_identity_unique').on(t.iss, t.kind, t.subject),
    check('principal_kind_check', oneOf(t.kind, PRINCIPAL_KINDS)),
  ],
);

export const membership = pgTable(
  'membership',
  {
    projectId: text()
      .notNull()
      .references(() => project.id),
    principalId: text()
      .notNull()
      .references(() => principal.id),
    role: text({ enum: values(Role.options) }).notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    primaryKey({ columns: [t.projectId, t.principalId] }),
    check('membership_role_check', oneOf(t.role, Role.options)),
  ],
);

/** Server mode (R1); unused in M1. */
export const invitation = pgTable(
  'invitation',
  {
    id: text().primaryKey(),
    projectId: text()
      .notNull()
      .references(() => project.id),
    emailNorm: text().notNull(),
    role: text({ enum: values(Role.options) }).notNull(),
    invitedBy: text()
      .notNull()
      .references(() => principal.id),
    expiresAt: timestamptz().notNull(),
    acceptedAt: timestamptz(),
    acceptedBy: text().references(() => principal.id),
    createdAt: createdAt(),
  },
  (t) => [
    unique('invitation_project_id_unique').on(t.projectId, t.id),
    index('invitation_project_email_idx').on(t.projectId, t.emailNorm),
    check('invitation_role_check', oneOf(t.role, Role.options)),
  ],
);

export const agentToken = pgTable(
  'agent_token',
  {
    id: text().primaryKey(),
    projectId: text()
      .notNull()
      .references(() => project.id),
    /** The token's own service principal (`iss = urn:proa:agent-token`). */
    principalId: text()
      .notNull()
      .unique('agent_token_principal_unique')
      .references(() => principal.id),
    name: text().notNull(),
    /** First 8 characters after `proa_at_`. */
    prefix: text().notNull(),
    /** sha256 (hex) of the full secret; the secret itself is never stored. */
    secretHash: text().notNull().unique('agent_token_secret_hash_unique'),
    scopes: text({ enum: values(AgentScope.options) })
      .array()
      .notNull(),
    expiresAt: timestamptz().notNull(),
    revokedAt: timestamptz(),
    createdBy: text()
      .notNull()
      .references(() => principal.id),
    lastUsedAt: timestamptz(),
    createdAt: createdAt(),
  },
  (t) => [
    unique('agent_token_project_id_unique').on(t.projectId, t.id),
    // Agent tokens never carry proa:review (CONCEPT §6).
    check(
      'agent_token_scopes_check',
      sql`cardinality(${t.scopes}) > 0 and ${t.scopes} <@ array[${sql.raw(
        AgentScope.options.map((s) => `'${s}'`).join(', '),
      )}]::text[]`,
    ),
  ],
);

export const model = pgTable(
  'model',
  {
    id: text().primaryKey(),
    projectId: text()
      .notNull()
      .references(() => project.id),
    /** Immutable model key, e.g. `billing/dunning`. */
    key: text().notNull(),
    name: text(),
    /** Null only inside the ingest transaction that creates the model. */
    headRevisionId: text(),
    /** Set when the model is deleted; a later upload of the same key revives it. */
    deletedSeq: seqColumn(),
    createdAt: createdAt(),
    updatedAt: timestamptz().notNull().defaultNow(),
  },
  (t): PgTableExtraConfigValue[] => [
    unique('model_project_key_unique').on(t.projectId, t.key),
    unique('model_project_id_unique').on(t.projectId, t.id),
    foreignKey({
      name: 'model_head_revision_fk',
      columns: [t.projectId, t.headRevisionId],
      foreignColumns: [modelRevision.projectId, modelRevision.id],
    }),
  ],
);

export const modelRevision = pgTable(
  'model_revision',
  {
    id: text().primaryKey(),
    projectId: text().notNull(),
    modelId: text().notNull(),
    rev: integer().notNull(),
    /** The uploaded bytes, verbatim. */
    xml: bytea().notNull(),
    contentHash: text().notNull(),
    factsHash: text().notNull(),
    factsVersion: text().notNull(),
    /** `c7`/`c8` from `ExtractResult.engine`; null if the file names neither (migration 0003 backfills older rows). */
    engine: text({ enum: values(Engine.options) }),
    /** `ExtractResult.processes` and `.messageFlows` of `@proa/bpmn-facts`. */
    processes: jsonb().$type<ProcessInfo[]>().notNull(),
    messageFlows: jsonb().$type<MessageFlowInfo[]>().notNull(),
    source: jsonb().$type<RevisionSource>().notNull(),
    principalId: text()
      .notNull()
      .references(() => principal.id),
    seq: seqColumn().notNull(),
    createdAt: createdAt(),
  },
  (t): PgTableExtraConfigValue[] => [
    unique('model_revision_project_id_unique').on(t.projectId, t.id),
    unique('model_revision_model_rev_unique').on(t.modelId, t.rev),
    check(
      'model_revision_engine_check',
      sql`${t.engine} is null or ${oneOf(t.engine, Engine.options)}`,
    ),
    foreignKey({
      name: 'model_revision_model_fk',
      columns: [t.projectId, t.modelId],
      foreignColumns: [model.projectId, model.id],
    }),
  ],
);

export const fact = pgTable(
  'fact',
  {
    revisionId: text().notNull(),
    projectId: text().notNull(),
    kind: text({ enum: values(FactKind.options) }).notNull(),
    elementId: text().notNull(),
    processId: text(),
    scope: text({ enum: values(FactScope.options) }).notNull(),
    eventDef: text({ enum: values(EventDef.options) }),
    label: text().notNull(),
    keyRaw: text().notNull(),
    keyNorm: text().notNull(),
    fingerprint: text().notNull(),
    attrs: jsonb().$type<FactAttrs>().notNull(),
  },
  (t) => [
    primaryKey({ columns: [t.revisionId, t.kind, t.elementId] }),
    foreignKey({
      name: 'fact_revision_fk',
      columns: [t.projectId, t.revisionId],
      foreignColumns: [modelRevision.projectId, modelRevision.id],
    }),
    // "Which processes throw message X" (CONCEPT §4).
    index('fact_project_kind_key_idx').on(t.projectId, t.kind, t.keyNorm),
    check('fact_kind_check', oneOf(t.kind, FactKind.options)),
    check('fact_scope_check', oneOf(t.scope, FactScope.options)),
    check(
      'fact_event_def_check',
      sql`${t.eventDef} is null or ${oneOf(t.eventDef, EventDef.options)}`,
    ),
  ],
);

export const relation = pgTable(
  'relation',
  {
    id: text().primaryKey(),
    projectId: text()
      .notNull()
      .references(() => project.id),
    type: text({ enum: values(RelationType.options) }).notNull(),
    fromRef: text().notNull(),
    toRef: text().notNull(),
    /** Model keys of both endpoints, for "relations touching model M". */
    fromModel: text()
      .notNull()
      .generatedAlwaysAs(sql`split_part(from_ref, '#', 1)`),
    toModel: text()
      .notNull()
      .generatedAlwaysAs(sql`split_part(to_ref, '#', 1)`),
    status: text({ enum: values(RelationStatus.options) }).notNull(),
    endpointState: text({ enum: values(EndpointState.options) }).notNull(),
    tier: text({ enum: values(Tier.options) }).notNull(),
    confidence: doublePrecision(),
    /** Incremented on every change (optimistic concurrency for decisions, M2). */
    version: integer().notNull().default(1),
    attrs: jsonb().$type<Record<string, unknown>>().notNull(),
    /** Endpoint fingerprints of the assertion the status rests on (endpoint_state compares against them). */
    fromFp: text(),
    toFp: text(),
    createdAt: createdAt(),
    updatedAt: timestamptz().notNull().defaultNow(),
  },
  (t) => [
    unique('relation_natural_key_unique').on(t.projectId, t.type, t.fromRef, t.toRef),
    unique('relation_project_id_unique').on(t.projectId, t.id),
    index('relation_from_model_idx').on(t.projectId, t.fromModel),
    index('relation_to_model_idx').on(t.projectId, t.toModel),
    check('relation_type_check', oneOf(t.type, RelationType.options)),
    check('relation_status_check', oneOf(t.status, RelationStatus.options)),
    check('relation_endpoint_state_check', oneOf(t.endpointState, EndpointState.options)),
    check('relation_tier_check', oneOf(t.tier, Tier.options)),
    check(
      'relation_confidence_check',
      sql`${t.confidence} is null or ${t.confidence} between 0 and 1`,
    ),
  ],
);

export const relationAssertion = pgTable(
  'relation_assertion',
  {
    id: text().primaryKey(),
    projectId: text().notNull(),
    relationId: text().notNull(),
    /** Seq of the event that recorded the assertion. */
    seq: seqColumn().notNull(),
    kind: text({ enum: ASSERTION_KINDS }).notNull(),
    verdict: text({ enum: VERDICTS }),
    /** Derived from the credential, never sent by clients (CONCEPT §6). */
    sourceKind: text({ enum: values(SourceKind.options) }).notNull(),
    principalId: text()
      .notNull()
      .references(() => principal.id),
    clientId: text(),
    /** Declared procedure and LLM model (agents). */
    declared: jsonb().$type<{ procedure: DeclaredProcedure | null; llmModel: string | null }>(),
    submissionId: text(),
    tier: text({ enum: values(Tier.options) }),
    confidence: doublePrecision(),
    /** Agent rationale, rejection reason, hold or accept note, or the text of a note. */
    rationale: text(),
    evidence: jsonb().$type<string[]>(),
    /** An agent's question to the reviewer, or the question of a hold. */
    question: text(),
    /** Label of a hold. */
    label: text(),
    /** `correct`: the manual relation accepted instead, or the corrected proposal. */
    linkedRelationId: text(),
    fromFp: text(),
    toFp: text(),
    /**
     * Basis of a pipeline proposal (judge each pair once): the `facts_hash`
     * of each endpoint's model as the judging agent saw it; null for every
     * other assertion and for proposals before procedure 0.2.0.
     */
    fromHash: text(),
    toHash: text(),
    createdAt: createdAt(),
  },
  (t): PgTableExtraConfigValue[] => [
    foreignKey({
      name: 'relation_assertion_relation_fk',
      columns: [t.projectId, t.relationId],
      foreignColumns: [relation.projectId, relation.id],
    }),
    foreignKey({
      name: 'relation_assertion_submission_fk',
      columns: [t.projectId, t.submissionId],
      foreignColumns: [analysisSubmission.projectId, analysisSubmission.id],
    }),
    index('relation_assertion_relation_idx').on(t.projectId, t.relationId, t.seq),
    // Agents only propose; humans (and the rule tier, for calls) decide.
    check(
      'relation_assertion_agents_never_decide',
      sql`not (${t.kind} = 'decision' and ${t.sourceKind} = 'agent')`,
    ),
    // Notes (answers to held questions) come from humans only.
    check(
      'relation_assertion_notes_by_humans',
      sql`${t.kind} <> 'note' or ${t.sourceKind} = 'human'`,
    ),
    check(
      'relation_assertion_verdict_check',
      sql`(${t.kind} = 'decision') = (${t.verdict} is not null) and (${t.verdict} is null or ${oneOf(t.verdict, VERDICTS)})`,
    ),
    check('relation_assertion_kind_check', oneOf(t.kind, ASSERTION_KINDS)),
    check('relation_assertion_source_kind_check', oneOf(t.sourceKind, SourceKind.options)),
    check(
      'relation_assertion_tier_check',
      sql`${t.tier} is null or ${oneOf(t.tier, Tier.options)}`,
    ),
    check(
      'relation_assertion_confidence_check',
      sql`${t.confidence} is null or ${t.confidence} between 0 and 1`,
    ),
  ],
);

export const analysisTask = pgTable(
  'analysis_task',
  {
    id: text().primaryKey(),
    projectId: text().notNull(),
    modelId: text().notNull(),
    revisionId: text().notNull(),
    kind: text({ enum: TASK_KINDS }).notNull(),
    factsHash: text().notNull(),
    state: text({ enum: TASK_STATES }).notNull(),
    leaseTokenHash: text(),
    claimedBy: text().references(() => principal.id),
    leaseUntil: timestamptz(),
    attempts: integer().notNull().default(0),
    lastError: text(),
    /** Seq of the latest `analysis.claimed` event: the project state the claim input shows. */
    claimedSeq: seqColumn(),
    /**
     * The typed pairs the latest claim must judge (its candidates minus
     * judged and skipped pairs); cleared when the task leaves `claimed`
     * without a submission.
     */
    assignment: jsonb().$type<TypedPair[]>(),
    /** A judgement this claim relied on was withdrawn: its submit queues a follow-up task. */
    requeueAfter: boolean().notNull().default(false),
    /** Seq of the `analysis.queued` event; orders tasks of a model (created_at ties within a transaction). */
    seq: seqColumn().notNull(),
    createdAt: createdAt(),
    updatedAt: timestamptz().notNull().defaultNow(),
  },
  (t) => [
    unique('analysis_task_project_id_unique').on(t.projectId, t.id),
    foreignKey({
      name: 'analysis_task_model_fk',
      columns: [t.projectId, t.modelId],
      foreignColumns: [model.projectId, model.id],
    }),
    foreignKey({
      name: 'analysis_task_revision_fk',
      columns: [t.projectId, t.revisionId],
      foreignColumns: [modelRevision.projectId, modelRevision.id],
    }),
    // One open task per model and kind (CONCEPT §2).
    uniqueIndex('analysis_task_open_unique')
      .on(t.modelId, t.kind)
      .where(sql`${t.state} in ('queued', 'claimed')`),
    index('analysis_task_model_idx').on(t.projectId, t.modelId, t.kind, t.seq),
    index('analysis_task_state_idx').on(t.state, t.createdAt),
    check('analysis_task_kind_check', oneOf(t.kind, TASK_KINDS)),
    check('analysis_task_state_check', oneOf(t.state, TASK_STATES)),
  ],
);

/** Submissions, stored verbatim for the eval (CONCEPT §3, §7). */
export const analysisSubmission = pgTable(
  'analysis_submission',
  {
    id: text().primaryKey(),
    projectId: text().notNull(),
    taskId: text().notNull().unique('analysis_submission_task_unique'),
    /** Client-chosen `submissionId` (UUID); replays return the stored result. */
    clientSubmissionId: text().notNull(),
    principalId: text()
      .notNull()
      .references(() => principal.id),
    /** Client of the credential (`agt_…`, `proa-web`, `proa-cli`). */
    clientId: text(),
    declared: jsonb().$type<{ procedure: DeclaredProcedure; llmModel: string | null }>().notNull(),
    /** The request as received, minus the lease token. */
    payload: jsonb().$type<Record<string, unknown>>().notNull(),
    result: jsonb().$type<SubmissionResult>().notNull(),
    seq: seqColumn().notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    unique('analysis_submission_project_id_unique').on(t.projectId, t.id),
    foreignKey({
      name: 'analysis_submission_task_fk',
      columns: [t.projectId, t.taskId],
      foreignColumns: [analysisTask.projectId, analysisTask.id],
    }),
  ],
);

/**
 * No-links (judge each pair once): an agent's judgement that a typed pair is
 * unrelated, stored from a submission with its basis (the `facts_hash` of
 * both endpoint models as the agent saw them). Append-only; live while it
 * has no `no_link_withdrawal` row.
 */
export const noLink = pgTable(
  'no_link',
  {
    id: text().primaryKey(),
    projectId: text().notNull(),
    type: text({ enum: LINK_TYPES }).notNull(),
    fromRef: text().notNull(),
    toRef: text().notNull(),
    /** Model keys of both endpoints (set on insert). */
    fromModel: text().notNull(),
    toModel: text().notNull(),
    fromHash: text().notNull(),
    toHash: text().notNull(),
    reason: text().notNull(),
    /** Derived from the credential (CONCEPT §6). */
    sourceKind: text({ enum: JUDGING_SOURCE_KINDS }).notNull(),
    principalId: text()
      .notNull()
      .references(() => principal.id),
    clientId: text(),
    declared: jsonb().$type<{ procedure: DeclaredProcedure; llmModel: string | null }>().notNull(),
    submissionId: text().notNull(),
    /** The analysed model (origin). */
    modelId: text().notNull(),
    /** Seq of the submission's `analysis.done` event. */
    seq: seqColumn().notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    unique('no_link_project_id_unique').on(t.projectId, t.id),
    unique('no_link_submission_pair_unique').on(t.submissionId, t.type, t.fromRef, t.toRef),
    foreignKey({
      name: 'no_link_submission_fk',
      columns: [t.projectId, t.submissionId],
      foreignColumns: [analysisSubmission.projectId, analysisSubmission.id],
    }),
    foreignKey({
      name: 'no_link_model_fk',
      columns: [t.projectId, t.modelId],
      foreignColumns: [model.projectId, model.id],
    }),
    index('no_link_from_model_idx').on(t.projectId, t.fromModel),
    index('no_link_to_model_idx').on(t.projectId, t.toModel),
    index('no_link_pair_idx').on(t.projectId, t.fromRef, t.toRef),
    index('no_link_principal_idx').on(t.projectId, t.principalId),
    check('no_link_type_check', oneOf(t.type, LINK_TYPES)),
    check('no_link_source_kind_check', oneOf(t.sourceKind, JUDGING_SOURCE_KINDS)),
  ],
);

/** The end of a no-link (supersession, replacement, token revocation); append-only. */
export const noLinkWithdrawal = pgTable(
  'no_link_withdrawal',
  {
    noLinkId: text()
      .primaryKey()
      .references(() => noLink.id),
    projectId: text().notNull(),
    /** Seq of the event that caused it (`analysis.done`, `agent_token.revoked`). */
    seq: seqColumn().notNull(),
    /** Who caused it. */
    principalId: text()
      .notNull()
      .references(() => principal.id),
    reason: text().notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    foreignKey({
      name: 'no_link_withdrawal_project_fk',
      columns: [t.projectId, t.noLinkId],
      foreignColumns: [noLink.projectId, noLink.id],
    }),
  ],
);

/** Change feed and audit log; append-only (trigger). */
export const event = pgTable(
  'event',
  {
    projectId: text()
      .notNull()
      .references(() => project.id),
    seq: seqColumn().notNull(),
    type: text().notNull(),
    principalId: text()
      .notNull()
      .references(() => principal.id),
    clientId: text(),
    subjectRef: text(),
    payload: jsonb().$type<Record<string, unknown>>().notNull(),
    at: timestamptz().notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.projectId, t.seq] })],
);

/**
 * Deterministic findings of the project head, recomputed by every ingest and
 * delete (derived state, replaced as a whole; not part of the history).
 */
export const finding = pgTable(
  'finding',
  {
    projectId: text()
      .notNull()
      .references(() => project.id),
    ord: integer().notNull(),
    kind: text({ enum: values(FindingKind.options) }).notNull(),
    refs: text().array().notNull(),
    detail: text().notNull(),
  },
  (t) => [
    primaryKey({ columns: [t.projectId, t.ord] }),
    check('finding_kind_check', oneOf(t.kind, FindingKind.options)),
  ],
);

/**
 * `model_pipeline` (CONCEPT §3): stage and open items per live model.
 * Stage from the latest non-cancelled `relations` task: queued →
 * waiting_for_agent, claimed → agent_working, failed → agent_failed, done →
 * waiting_for_review (any proposed item, or an accepted relation whose
 * endpoint is not ok), waiting_for_clarification (only held items),
 * incorporated. Open items: relations touching the model that are proposed,
 * held, or accepted with endpoint_state ≠ ok.
 */
export const modelPipeline = pgView('model_pipeline', {
  projectId: text('project_id').notNull(),
  modelId: text('model_id').notNull(),
  modelKey: text('model_key').notNull(),
  taskState: text('task_state', { enum: TASK_STATES }),
  reviewItems: integer('review_items').notNull(),
  heldItems: integer('held_items').notNull(),
  openItems: integer('open_items').notNull(),
  stage: text('stage').notNull(),
}).as(sql`
  select m.project_id, m.id as model_id, m.key as model_key, t.state as task_state,
         r.review_items, r.held_items, r.review_items + r.held_items as open_items,
         case
           when t.state = 'claimed' then 'agent_working'
           when t.state = 'failed' then 'agent_failed'
           when t.state = 'done' then case
             when r.review_items > 0 then 'waiting_for_review'
             when r.held_items > 0 then 'waiting_for_clarification'
             else 'incorporated' end
           else 'waiting_for_agent'
         end as stage
  from model m
  left join lateral (
    select a.state from analysis_task a
    where a.project_id = m.project_id and a.model_id = m.id
      and a.kind = 'relations' and a.state <> 'cancelled'
    order by a.seq desc
    limit 1
  ) t on true
  cross join lateral (
    select
      (count(*) filter (where x.status = 'proposed'
        or (x.status = 'accepted' and x.endpoint_state <> 'ok')))::int as review_items,
      (count(*) filter (where x.status = 'held'))::int as held_items
    from relation x
    where x.project_id = m.project_id and (x.from_model = m.key or x.to_model = m.key)
  ) r
  where m.deleted_seq is null
`);
