/**
 * `@proa/procedures`: the analysis instructions for agents (CONCEPT §7),
 * written once as `packages/procedures/<name>.md` with frontmatter `id`,
 * `version`, `title`, `status` and optionally `description`. MCP
 * `get_procedure` serves them; the MCP prompt `work_pipeline` and the Claude
 * Code skill `/proa:relations` (`plugins/proa`, generated by
 * `pnpm --filter @proa/procedures generate`) wrap the same text
 * (`wrappers.ts`); so do the skill `/proa:placements` and, for ad-hoc work,
 * the MCP prompt `place_processes`.
 *
 * Status: `proa-relations@0.2.0` (`relations.md`; 0.1.0 released with M3,
 * 0.2.0 judges each pair once) and `proa-placements@0.1.0` (`placements.md`,
 * M4b, frontmatter `kind: placement`: the claims name that task kind). The
 * interactive prompt `draft_value_chain` is no versioned procedure; its text
 * is in `prompts/` (`prompts.ts`), which {@link listProcedures} never reads.
 */
import { readFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { ProcedureFormatError } from './errors.ts';

export { ProcedureFormatError };

/** Directory holding the procedure Markdown files (the package root). */
export const PROCEDURES_DIR = fileURLToPath(new URL('..', import.meta.url));

export interface Procedure {
  /** E.g. `proa-relations`; agents declare `<id>@<version>` with their submissions. */
  id: string;
  /** Semantic version, e.g. `0.1.0`. */
  version: string;
  title: string;
  /** `placeholder` until the real procedure ships, then `released`. */
  status: string;
  /** One line on what the procedure does; the Claude Code skill's description. */
  description?: string;
  /**
   * The task kind its claims name (`kinds`), from the frontmatter: `placement`
   * for `proa-placements`; left out for `proa-relations` (the server's default kind).
   */
  kind?: string;
  /** File name without `.md`, accepted as an alias of `id` (`relations`). */
  name: string;
  /** The Markdown body without frontmatter. */
  text: string;
}

const FRONTMATTER = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?/;
const REQUIRED = ['id', 'version', 'title', 'status'] as const;

/**
 * Parses one procedure file: `key: value` lines between `---` fences, then
 * the Markdown body.
 *
 * @throws {ProcedureFormatError} if the frontmatter is missing or incomplete
 */
export function parseProcedure(name: string, source: string): Procedure {
  const m = FRONTMATTER.exec(source);
  if (!m?.[1]) throw new ProcedureFormatError(`${name}: missing frontmatter`);
  const fields = new Map<string, string>();
  for (const line of m[1].split(/\r?\n/)) {
    const kv = /^([A-Za-z][\w-]*):\s*(.*)$/.exec(line.trim());
    if (kv?.[1] && kv[2] !== undefined) fields.set(kv[1], kv[2].replace(/^(['"])(.*)\1$/, '$2'));
  }
  for (const key of REQUIRED) {
    if (!fields.get(key)) throw new ProcedureFormatError(`${name}: frontmatter lacks ${key}`);
  }
  if (!/^\d+\.\d+\.\d+$/.test(fields.get('version') ?? '')) {
    throw new ProcedureFormatError(`${name}: version must be semver (x.y.z)`);
  }
  const description = fields.get('description');
  const kind = fields.get('kind');
  return {
    id: fields.get('id') ?? '',
    version: fields.get('version') ?? '',
    title: fields.get('title') ?? '',
    status: fields.get('status') ?? '',
    ...(description ? { description } : {}),
    // Only when present, so a procedure without it parses as before.
    ...(kind ? { kind } : {}),
    name,
    text: source.slice(m[0].length).trim(),
  };
}

let cache: Procedure[] | undefined;

/** Every procedure in {@link PROCEDURES_DIR}, sorted by id (read once). */
export function listProcedures(): Procedure[] {
  cache ??= readdirSync(PROCEDURES_DIR)
    .filter((f) => f.endsWith('.md') && f.toLowerCase() !== 'readme.md')
    .map((f) => parseProcedure(f.slice(0, -3), readFileSync(`${PROCEDURES_DIR}/${f}`, 'utf8')))
    .sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
  return cache;
}

/** A procedure by `id` (`proa-relations`) or file name (`relations`); `null` if unknown. */
export function getProcedure(idOrName: string): Procedure | null {
  return listProcedures().find((p) => p.id === idOrName || p.name === idOrName) ?? null;
}

export { PLUGIN_VERSION, pipelineProcedures } from './plugin.ts';
export { DRAFT_VALUE_CHAIN_FILE, PROMPTS_DIR, renderDraftValueChainPrompt } from './prompts.ts';
export {
  MAX_PIPELINE_TASKS,
  SKILL_ARGUMENT_HINT,
  claimKinds,
  renderAdHocWrapper,
  renderPipelineWrapper,
  renderSkill,
  skillPath,
  type PipelineScope,
} from './wrappers.ts';
